name: First Workflow
on:
  push:
    branches:
      - main
      - 'destroy/*'
  workflow_dispatch:
  pull_request:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Create File" >> file.txt
      - name: Print Working Directory
        run: pwd
      - name: List Directory Contents
        run: ls -ltr
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
      - name: Print goodbye
        run: echo "Done - bye!"
