name: First Workflow
on:
  pull_request_review:
    types: [submitted]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "This is a destroy branch"
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
        continue-on-error: true
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Print only on Push
        if: github.event.review.state == 'approved'
        run: echo "This PR was approved"      
