name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
     branches:
       - "destroy/*"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "This is a destroy branch"
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
      - name: Print goodbye
        run: echo "Done - bye!"
