name: First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World"
            echo "It Me Again"
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
      - name: Print goodbye
        run: echo "Done - bye!"
