name: First Workflow
on:
  push:
    branches:
      - main
      - 'destroy/*'
  workflow_dispatch:
  pull_request:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "This is a destroy branch"
      - name: Print Context
        run: echo "${{ toJSON(github) }}"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Print only on Push
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: echo "Print Only on Push"      
